services:
  postgres:
    image: postgres:16
    container_name: clinicsense-postgres
    environment:
      POSTGRES_DB: clinicsense
      POSTGRES_USER: clinicsense
      POSTGRES_PASSWORD: devpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: clinicsense-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data: