# Purpose:
# This file intercepts the AI's generated query plan and validates it before execution.
#
# Why this file exists:
# We cannot trust the AI blindly. Even if we told the AI not to delete data, it might
# hallucinate a 'delete' command. This file explicitly checks the database rules
# (dataset_registry.allowed_operations) to ensure the AI's plan is 100% safe to run.
#
# In simple terms:
# The AI writes a shopping list. This file takes the list, checks it against the user's 
# budget and dietary restrictions, and then actually walks down the aisles to get the groceries.

import asyncio
from typing import List
from sqlalchemy.orm import Session
from app.ai.schemas import QueryPlan, ExecutionStep
from app.connectors.factory import get_connector
from app.connectors.base import NormalizedResult
from app.db.semantic_models import DatasetRegistry

async def execute_plan(db: Session, plan: QueryPlan, current_user) -> List[NormalizedResult]:
    """
    Validates and executes a QueryPlan generated by Groq.
    """
    results = []
    
    # 1. Safety Check: Did the AI get confused?
    if plan.needs_clarification:
        # If the AI flagged that it didn't understand the user's question,
        # we abort execution entirely so we don't return random data.
        return results

    for step in plan.steps:
        # 2. Database Lookup: Fetch the real dataset configurations
        dataset = db.query(DatasetRegistry).filter(
            DatasetRegistry.id == step.dataset_id
        ).first()
        
        if not dataset:
            raise ValueError(f"Validation failed: Dataset {step.dataset_id} does not exist.")
            
        # 3. RBAC Defense-in-Depth
        # (In a full app, you re-verify current_user has access to dataset.module_id here)
            
        # 4. Strict Allowlist Check
        if step.operation not in dataset.allowed_operations:
            raise PermissionError(
                f"Security blocked: AI attempted an unauthorized '{step.operation}' "
                f"operation on dataset '{dataset.description}'."
            )
            
        # 5. Route to the correct connector
        connector = get_connector(dataset.connector_type)
        
        # 6. Translate AI's semantic ID to physical source reference (e.g., table name)
        # We override the dataset_id in the step with the actual source_ref so the 
        # connector knows exactly what table, API, or file to query.
        execution_step = step.model_copy(update={"dataset_id": dataset.source_ref})
        
        # 7. Execute the safe, parameterized fetch
        result = await connector.fetch(execution_step)
        results.append(result)
        
    return results