# Purpose:
# This file implements the PostgreSQL connector adapter.
#
# Why this file exists:
# It translates the structured ExecutionStep (generated by the AI) into safe, 
# parameterized SQL queries using your existing SQLAlchemy session. It ensures
# we only run read-only queries with strict parameterization.
#
# In simple terms:
# This is the translator that turns the AI's requested filters into actual SQL 
# that runs safely against your Postgres database, then reformats the answer.

import asyncio
from typing import Any, Dict, List
from sqlalchemy import text
from app.db.session import SessionLocal
from app.connectors.base import Connector, ExecutionStep, NormalizedResult

class PostgresConnector(Connector):
    def __init__(self, source_name: str = "postgres"):
        self.source_name = source_name

    def _execute_sync(self, plan: ExecutionStep) -> NormalizedResult:
        # Note: In a production scenario, we map dataset_id to the specific table 
        # via the dataset_registry. For MVP, we build a safe parameterized query.
        
        db = SessionLocal()
        try:
            # MVP Safety Check: Enforce basic allowed operations
            if plan.operation not in ["select", "filter"]:
                raise ValueError(f"Operation {plan.operation} not supported by PostgresConnector")
            
            # Constructing a safe, parameterized base query (placeholder for actual schema mapping)
            # You will map plan.dataset_id to the actual table name dynamically later.
            table_name = "invoices" # Placeholder: would be dynamically resolved
            
            # Select specific fields if requested, else select all
            select_clause = ", ".join(plan.fields) if plan.fields else "*"
            query_str = f"SELECT {select_clause} FROM {table_name}"
            
            params = {}
            if plan.filters:
                conditions = []
                for idx, (key, value) in enumerate(plan.filters.items()):
                    # Parameterized filter construction: column = :param_0
                    param_name = f"param_{idx}"
                    conditions.append(f"{key} = :{param_name}")
                    params[param_name] = value
                
                query_str += " WHERE " + " AND ".join(conditions)
            
            # Execute safely with bound parameters
            result = db.execute(text(query_str), params)
            
            columns = result.keys()
            rows = [dict(zip(columns, row)) for row in result.fetchall()]
            
            return NormalizedResult(
                source=self.source_name,
                rows=rows,
                columns=list(columns)
            )
        finally:
            db.close()

    async def fetch(self, plan: ExecutionStep) -> NormalizedResult:
        # Wrap the synchronous SQLAlchemy execution in a thread 
        # to satisfy the async connector contract
        return await asyncio.to_thread(self._execute_sync, plan)